# Generated by Django 5.1.6 on 2025-02-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_category', models.CharField(choices=[('SEEDS', 'Seeds'), ('FRUITS', 'Fruits'), ('VEGETABLES', 'Vegetables'), ('FLOWER', 'Flower'), ('DAIRY', 'Eggs and Milk')], max_length=20)),
                ('name', models.CharField(max_length=300)),
                ('trending', models.BooleanField(default=False, null=True)),
                ('discounts', models.BooleanField(default=False, null=True)),
                ('imgage', models.FileField(null=True, upload_to='static/uploads')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('p_quantity', models.IntegerField()),
                ('p_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('p_sale', models.DecimalField(decimal_places=0, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('p_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
