# Generated by Django 5.1.6 on 2025-02-09 21:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_category', models.CharField(choices=[('SEEDS', 'Seeds'), ('FRUITS', 'Fruits'), ('VEGETABLES', 'Vegetables'), ('FLOWER', 'Flower'), ('DAIRY', 'Eggs and Milk')], max_length=20)),
                ('name', models.CharField(max_length=300)),
                ('trending', models.BooleanField(default=False, null=True)),
                ('discounts', models.BooleanField(default=False, null=True)),
                ('image', models.FileField(null=True, upload_to='static/uploads')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('p_quantity', models.IntegerField()),
                ('p_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('p_sale', models.DecimalField(decimal_places=0, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('p_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('consumer', 'Consumer'), ('business', 'Business')], default='consumer', max_length=20),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
    ]
